import { bool, cleanEnv, num, port, str } from "envalid";

export const env = cleanEnv(process.env, {
  DATABASE_URL: str(),
  NODE_ENV: str({ default: "development" }),
  PORT: port({ default: 4000 }),
  FRONTEND_URL: str({ default: "http://localhost:3000" }),
  APP_URL: str({ default: "http://localhost:4000" }),
  CLERK_SECRET_KEY: str({ default: "" }),
  CLERK_WEBHOOK_SECRET: str({ default: "" }),
  GEMINI_API_KEY: str({ default: "" }),
  GEMINI_IMAGE_MODEL: str({ default: "gemini-3-pro-image-preview" }),
  GEMINI_PREVIEW_MODEL: str({ default: "" }),
  GEMINI_TEXT_MODEL: str({ default: "gemini-2.5-flash" }),
  GEMINI_MAX_CONCURRENT: num({ default: 3 }),
  ENABLE_DEMO_GENERATION: bool({ default: true }),
  R2_ACCOUNT_ID: str({ default: "" }),
  R2_ACCESS_KEY: str({ default: "" }),
  R2_SECRET_KEY: str({ default: "" }),
  R2_BUCKET: str({ default: "sahm-portraits" }),
  R2_ENDPOINT: str({ default: "" }),
  R2_PUBLIC_URL: str({ default: "" }),
  STRIPE_SECRET_KEY: str({ default: "" }),
  STRIPE_WEBHOOK_SECRET: str({ default: "" }),
  STRIPE_PRICE_SINGLE: str({ default: "" }),
  STRIPE_PRICE_MEMORIAL: str({ default: "" }),
  STRIPE_PRICE_PREMIUM: str({ default: "" }),
  RESEND_API_KEY: str({ default: "" }),
  RESEND_FROM_EMAIL: str({ default: "hello@getsahm.com" }),
  JWT_SECRET: str({ default: "replace-me" }),
  PRINTFUL_API_TOKEN: str({ default: "" }),
  PRINTFUL_WEBHOOK_SECRET: str({ default: "" }),
});

export const isProduction = env.NODE_ENV === "production";
